INSERT OR IGNORE INTO main.CHARACTER(NAME, IMAGE_NAME, FIGHTERS_PASS) VALUES
('Banjo & Kazooie', 'banjo-kazooie', 1),
('Bayonetta', 'bayonetta', 0),
('Bowser', 'bowser', 0),
('Bowser Jr.', 'bowser-jr', 0),
('Byleth', 'byleth', 1),
('Captain Falcon', 'captain-falcon', 0),
('Chrom', 'chrom', 0),
('Cloud', 'cloud', 0),
('Corrin', 'corrin', 0),
('Daisy', 'daisy', 0),
('Dark Pit', 'dark-pit', 0),
('Dark Samus', 'dark-samus', 0),
('Diddy Kong', 'diddy-kong', 0),
('Donkey Kong', 'donkey-kong', 0),
('Dr. Mario', 'dr-mario', 0),
('Duck Hunt', 'duck-hunt', 0),
('Falco', 'falco', 0),
('Ganondorf', 'ganondorf', 0),
('Greninja', 'greninja', 0),
('Hero', 'hero', 1),
('Ice Climbers', 'ice-climbers', 0),
('Ike', 'ike', 0),
('Incineroar', 'incineroar', 0),
('Inkling', 'inkling', 0),
('Isabelle', 'isabelle', 0),
('Jigglypuff', 'jigglypuff', 0),
('Joker', 'joker', 1),
('Kazuya', 'kazuya', 2),
('Ken', 'ken', 0),
('King Dedede', 'king-dedede', 0),
('King R Rool', 'king-k-rool', 0),
('Kirby', 'kirby', 0),
('Link', 'link', 0),
('Little Mac', 'little-mac', 0),
('Lucario', 'lucario', 0),
('Lucas', 'lucas', 0),
('Lucina', 'lucina', 0),
('Luigi', 'luigi', 0),
('Mario', 'mario', 0),
('Marth', 'marth', 0),
('Megaman', 'megaman', 0),
('Meta Knight', 'meta-knight', 0),
('Mewtwo', 'mewtwo', 0),
('Mii Brawler', 'mii-brawler', 0),
('Mii Gunner', 'mii-gunner', 0),
('Mii Sword Fighter', 'mii-sword-fighter', 0),
('Min Min', 'min-min', 2),
('Mr Game & Watch', 'mr-game-and-watch', 0),
('Ness', 'ness', 0),
('Olimar', 'olimar', 0),
('Pacman', 'pacman', 0),
('Palutena', 'palutena', 0),
('Peach', 'peach', 0),
('Pichu', 'pichu', 0),
('Pikachu', 'pikachu', 0),
('Piranha Plant', 'piranha-plant', 0), -- Count Piranha Plant in base game since it was free to grab for a while
('Pit', 'pit', 0),
('Pokemon Trainer', 'pokemon-trainer', 0),
('Pyra/Mythra', 'pyra-mythra', 2),
('Richter', 'richter', 0),
('Ridley', 'ridley', 0),
('ROB', 'rob', 0),
('Robin', 'robin', 0),
('Rosalina', 'rosalina', 0),
('Roy', 'roy', 0),
('Ryu', 'ryu', 0),
('Samus', 'Samus', 0),
('Sephiroth', 'sephiroth', 2),
('Sheik', 'sheik', 0),
('Shulk', 'shulk', 0),
('Simon', 'simon', 0),
('Snake', 'snake', 0),
('Sonic', 'sonic', 0),
('Sora', 'sora', 2),
('Steve', 'steve', 2),
('Terry', 'terry', 1),
('Toon Link', 'toon-link', 0),
('Villager', 'villager', 0),
('Wario', 'wario', 0),
('Wii Fit', 'wii-fit', 0),
('Wolf', 'wolf', 0),
('Yoshi', 'yoshi', 0),
('Young Link', 'young-link', 0),
('Zelda', 'zelda', 0),
('Zero Suit Samus', 'zero-suit-samus', 0)